"""added initialization and models

Revision ID: 9a00191ed1e4
Revises:
Create Date: 2026-03-20 09:02:20.648593

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "9a00191ed1e4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
